Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'lib/tasks/*'
    - 'config/**/*'
    - 'bin/*'
    - 'app/channels/application_cable/connection.rb'
    - 'app/channels/application_cable/channel.rb'

Rails:
  Enabled: true 

Style/Encoding:
  EnforcedStyle: when_needed

Style/IndentationConsistency:
  EnforcedStyle: rails

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false